# Use Python37
FROM python:3.7
# Allow statements and log messages to immediately appear in the Knative logs
EXPOSE 5000

WORKDIR app

COPY * /app/

RUN apt update
RUN apt install -y libsndfile1-dev
RUN pip install -r requirements.txt
RUN python -m nltk.downloader punkt

CMD ["python", "app.py"]