# Use Python37
FROM python:3.8
# Allow statements and log messages to immediately appear in the Knative logs
EXPOSE 5000

WORKDIR app

COPY * /app/

RUN apt update
RUN apt install -y libsndfile1-dev
RUN apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg
RUN pip install -r requirements.txt
RUN python -m nltk.downloader punkt -d /usr/local/nltk_data

CMD ["python", "app.py"]